ToyShop.Web/Models/Toy.cs
// <copyright file="Toy.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace ToyShop.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Threading.Tasks;

    /// <summary>
    /// A view model for the Data.Models.Toy.
    /// </summary>
    public class Toy
    {
        /// <summary>
        /// Gets or sets the id of Toy from Data.Models.
        /// </summary>
        [Display(Name = "ID")]
        [Required]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the name of Toy from Data.Models.
        /// </summary>
        [Display(Name = "Name")]
        [Required]
        [StringLength(50, MinimumLength = 4)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the manufacturer of Toy from Data.Models.
        /// </summary>
        [Display(Name = "Manufacturer")]
        [Required]
        [StringLength(50, MinimumLength = 4)]
        public string Manufacturer { get; set; }

        /// <summary>
        /// Gets or sets the category of Toy from Data.Models.
        /// </summary>
        [Display(Name = "Category")]
        [Required]
        [StringLength(50, MinimumLength = 4)]
        public string Category { get; set; }

        /// <summary>
        /// Gets or sets the category of Toy from Data.Models.
        /// </summary>
        [Display(Name = "Quantity")]
        [Required]
        public int Quantity { get; set; }

        /// <summary>
        /// Gets or sets the price of Toy from Data.Models.
        /// </summary>
        [Display(Name = "Price")]
        [Required]
        public int Price { get; set; }
    }
}

ToyShop.Web/Models/ToyListViewModel.cs
// <copyright file="ToyListViewModel.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace ToyShop.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    /// <summary>
    /// Viewmodel for all of the toys from the database.
    /// </summary>
    public class ToyListViewModel
    {
        /// <summary>
        /// Gets or sets a list of toys from the database.
        /// </summary>
        public List<Toy> ListOfToys { get; set; }

        /// <summary>
        /// Gets or sets the selected toy to edit.
        /// </summary>
        public Toy EditableToy { get; set; }
    }
}

ToyShop.Web/Controllers/ToysController.cs
// <copyright file="ToysController.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace ToyShop.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using AutoMapper;
    using Microsoft.AspNetCore.Mvc;
    using ToyShop.Logic;
    using ToyShop.Web.Models;

    /// <summary>
    /// Controller class for actions on the Toys part of the web page.
    /// </summary>
    public class ToysController : Controller
    {
        private IShopLogic logic;
        private IMapper mapper;
        private ToyListViewModel vm;

        /// <summary>
        /// Initializes a new instance of the <see cref="ToysController"/> class.
        /// </summary>
        /// <param name="logic">Logic needed for db changes.</param>
        /// <param name="mapper">Mapper for coversions.</param>
        public ToysController(IShopLogic logic, IMapper mapper)
        {
            this.logic = logic;
            this.mapper = mapper;

            this.vm = new ToyListViewModel();
            this.vm.EditableToy = new Models.Toy();

            var toys = this.logic.GetAllToys();
            this.vm.ListOfToys = this.mapper.Map<IList<Data.Toy>, List<Models.Toy>>(toys);
        }

        /// <summary>
        /// The main index page.
        /// </summary>
        /// <returns>The index pages view.</returns>
        public IActionResult Index()
        {
            this.ViewData["editAction"] = "AddNew";
            return this.View("ToyIndex", this.vm);
        }

        // GET: Toys/Details/id

        /// <summary>
        /// The detail view page of an entity.
        /// </summary>
        /// <param name="id">The id of the entity.</param>
        /// <returns>The detail view of an entity.</returns>
        public IActionResult Details(int id)
        {
            return this.View("ToyDetails", this.GetToyModel(id));
        }

        // GET: Toys/Remove/id

        /// <summary>
        /// Removes an entitity from the database, and the page.
        /// </summary>
        /// <param name="id">Id of the removable entity.</param>
        /// <returns>The new updated view.</returns>
        public IActionResult Remove(int id)
        {
            this.TempData["editResult"] = "Delete FAILED!";

            if (this.logic.DeleteToy(id))
            {
                this.TempData["editResult"] = "Delete SUCCEEDED!";
            }

            return this.RedirectToAction(nameof(this.Index));
        }

        // GET: Toys/Edit/id

        /// <summary>
        /// Edits the toy with the given id.
        /// </summary>
        /// <param name="id">Id of the editably toy.</param>
        /// <returns>The edited.</returns>
        public IActionResult Edit(int id)
        {
            this.ViewData["editAction"] = "Edit";
            this.vm.EditableToy = this.GetToyModel(id);
            return this.View("ToyIndex", this.vm);
        }

        // POST: Toys/Edit/ + 1 toy + editAction

        /// <summary>
        /// Edits the toy with the given id.
        /// </summary>
        /// <param name="toy">The editable toy.</param>
        /// <param name="editAction">The edit action.</param>
        /// <returns>The refreshed index page.</returns>
        [HttpPost]
        public IActionResult Edit(Models.Toy toy, string editAction)
        {
            if (this.ModelState.IsValid && toy != null)
            {
                this.TempData["editResult"] = "Edit SUCCEEDED!";
                if (editAction == "AddNew")
                {
                    this.logic.AddToy(new Data.Toy() { Name = toy.Name, Manufacturer = toy.Manufacturer, Category = toy.Category, Quantity = toy.Quantity, Price = toy.Price });
                }
                else
                {
                    Data.Toy someToy = this.logic.GetToy(toy.Id);
                    if (someToy.Name != toy.Name)
                    {
                        if (!this.logic.UpdateToyName(toy.Id, toy.Name))
                        {
                            this.TempData["editResult"] = "Edit FAILED!";
                        }
                    }

                    if (someToy.Manufacturer != toy.Manufacturer)
                    {
                        if (!this.logic.UpdateToyManufacturer(toy.Id, toy.Manufacturer))
                        {
                            this.TempData["editResult"] = "Edit FAILED!";
                        }
                    }

                    if (someToy.Price != toy.Price)
                    {
                        if (!this.logic.UpdateToyPrice(toy.Id, toy.Price))
                        {
                            this.TempData["editResult"] = "Edit FAILED!";
                        }
                    }

                    if (someToy.Quantity != toy.Quantity)
                    {
                        if (!this.logic.UpdateToyQuantity(toy.Id, toy.Quantity))
                        {
                            this.TempData["editResult"] = "Edit FAILED!";
                        }
                    }

                    if (someToy.Category != toy.Category)
                    {
                        if (!this.logic.UpdateToyCategory(toy.Id, toy.Category))
                        {
                            this.TempData["editResult"] = "Edit FAILED!";
                        }
                    }
                }

                return this.RedirectToAction(nameof(this.Index));
            }
            else
            {
                this.ViewData["editAction"] = "Edit";
                this.vm.EditableToy = toy;
                return this.View("ToyIndex", this.vm);
            }
        }

        private Models.Toy GetToyModel(int id)
        {
            Data.Toy oneToy = this.logic.GetToy(id);
            return this.mapper.Map<Data.Toy, Models.Toy>(oneToy);
        }
    }
}

ToyShop.Web/Views/Toys/ToyDetails.cshtml
@model ToyShop.Web.Models.Toy

@{ 
    ViewData["Title"] = "ToyDetails";
}

<h1>Toy data:</h1>

<br/>
@Html.ActionLink("Back to the list", "Index")
<br/>

<table>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Id)</td>
        <td>@Html.DisplayFor(m => m.Id)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Name)</td>
        <td>@Html.DisplayFor(m => m.Name)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Manufacturer)</td>
        <td>@Html.DisplayFor(m => m.Manufacturer)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Quantity)</td>
        <td>@Html.DisplayFor(m => m.Quantity)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Price)</td>
        <td>@Html.DisplayFor(m => m.Price)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Category)</td>
        <td>@Html.DisplayFor(m => m.Category)</td>
    </tr>
</table>

ToyShop.Web/Views/Toys/ToyEditor.cshtml
@model ToyShop.Web.Models.Toy

<h3>Toy Editor</h3>

@using (Html.BeginForm("Edit", "Toys"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.Id)
    @Html.Hidden("editAction", ViewData["editAction"].ToString())

    <div class="editor-label">@Html.LabelFor(m => m.Name)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Name)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Manufacturer)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Manufacturer)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Category)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Category)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Quantity)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Quantity)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Price)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Price)</div>
    <br />

    <input type="submit" value="SEND" />
    <br />
}

ToyShop.Web/Views/Toys/ToyIndex.cshtml
@model ToyShop.Web.Models.ToyListViewModel

@{ 
    ViewData["Title"] = "ToysIndex";
}

<h1>Toys Index</h1><br />

<p style="color:red">@TempData["editResult"]</p>

@await Html.PartialAsync("ToyEditor", Model.EditableToy) 

@await Html.PartialAsync("ToyList", Model.ListOfToys) 

ToyShop.Web/Views/Toys/ToyList.cshtml
@model IEnumerable<ToyShop.Web.Models.Toy>

<h3>Toy List</h3>

@if (Model.Count() == 0)
{
    <p>No data in database</p>
}
else
{
    <table>
        <tr>
            <th>@Html.DisplayNameFor(m => m.First().Name)</th>
            <th>@Html.DisplayNameFor(m => m.First().Manufacturer)</th>
            <th>@Html.DisplayNameFor(m => m.First().Price)</th>
            <th>Datasheet</th>
            <th>Delete</th>
            <th>Edit</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(m => item.Name)</td>
                <td>@Html.DisplayFor(m => item.Manufacturer)</td>
                <td>@Html.DisplayFor(m => item.Price)</td>
                <td>@Html.ActionLink("<SHOW>", "Details", new { id = item.Id})</td>
                <td>@Html.ActionLink("<DELETE>", "Remove", new { id = item.Id})</td>
                <td>@Html.ActionLink("<EDIT>", "Edit", new { id = item.Id})</td>
            </tr>
        }
    </table>
}